name: Run Tests

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  test:
    name: Check my code!
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Check types
        run: yarn check:types

      - name: Run ESLint
        run: yarn lint
